version: '3.7'
services:
  oracledb:
    image: gvenzl/oracle-xe
    container_name: oracledb
    environment:
      - ORACLE_PASSWORD=oracle
    ports:
      - 1521:1521
    restart: unless-stopped
    networks:
      ghnetwork:
        ipv4_address: 172.20.0.5
    volumes:
      - ghoraclev:/opt/oracle/oradata
  uiserver:
    image: dbzadnen/ghuiserver
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    ports:
      - 8144:80
    networks:
      ghnetwork:
        ipv4_address: 172.20.0.4
  restapiserver:
    image: dbzadnen/ghrestapiserver
    environment:
      - SERVER_PORT=80
      - DB_PASSWORD=$DB_PASSWORD
      - DB_USER=$DB_USER
      - DB_CONNECT=$DB_CONNECT
      - NODE_ENV=production
    restart: unless-stopped
    scale: 3
    depends_on:
      - oracledb
    networks:
      - ghnetwork
  ghserver:
    image: dbzadnen/ghserver
    container_name: ghserver
    ports:
      - 8188:80
    restart: unless-stopped
    depends_on:
      - uiserver
      - restapiserver
    networks:
      ghnetwork:
        ipv4_address: 172.20.0.3
networks:
  ghnetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/24
volumes:
  ghoraclev: