version: '3.6'
services:
  oracledb:
    image: gvenzl/oracle-xe
    container_name: oracledb
    environment:
      - ORACLE_PASSWORD=oracle
    ports:
      - 1521:1521
    volumes:
      - /DB/OracleData/:/u01/app/oracle/oradata
