version: '3.7'
services:
  oracledb:
    image: gvenzl/oracle-xe
    container_name: oracledb
    environment:
      - ORACLE_PASSWORD=oracle
    ports:
      - 1521:1521
    restart: unless-stopped
    volumes:
      - ./DB/OracleData/:/u01/app/oracle/oradata
  uiserver:
    image: dbzadnen/ghuiserver
    container_name: uiserver
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    ports:
      - 8123:80
  restapiserver:
    image: dbzadnen/ghrestapiserver
    container_name: restapiserver
    environment:
      - SERVER_PORT=80
      - DB_PASSWORD=$DB_PASSWORD
      - DB_USER=$DB_USER
      - DB_CONNECT=$DB_CONNECT
      - NODE_ENV=production
    ports:
      - 8124:80
    restart: unless-stopped
    depends_on:
      - oracledb
  ghserver:
    image: dbzadnen/ghserver
    container_name: ghserver
    ports:
      - 8188:80
    restart: unless-stopped
    depends_on:
      - uiserver
      - restapiserver